### ISSUE TITLE
Carga de Checklist

### ISSUE THREAD

**Issue by IvanAP1791** [practica-final/Sistema-Checklist#3]
- [x] Datos del Conductor(Auto-Generados)
- [x] Seleccion del Vehiculo (Por Patente)
- [x] Documentacion del Vehiculo
- [x] Tablero vehiculo
- [x] Laterales
- [x] Seccion trasera
- [x] Frente
- [x] Comentarios adjuntos
- [x] Fotos
