### ISSUE TITLE
Gestión de Checklist

### ISSUE THREAD

**Issue by IvanAP1791** [practica-final/Sistema-Checklist#4]
Se detallarán una lista a modo de control de tablero:

- Checklist Rechazados
- [ ] Nro de Checklist
- [ ] Vehículo
- [ ] Conductor
- [ ] Fecha de solicitud
- [ ] Consulta (¿Qué faltó?)
- Checklist Aprobados
- [ ] Nro de Checklist
- [ ] Vehículo
- [ ] Conductor
- [ ] Fecha de solicitud
- [ ] Consulta (muestreo de todos los datos cargados)
